# Network Info
NETWORK_PASSPHRASE="Pi Testnet"
HORIZON_URL="https://api.testnet.minepi.com"

# Organization Info
ORG_NAME="USD1"
ORG_URL="https://dealway.netlify.app"
ORG_DESCRIPTION="usd1"
ORG_LOGO="https://dealway.netlify.app/logo.png"

# Token Info
[[CURRENCIES]]
code="USD1"
issuer="GBQ3H472BMOMTFRSK5P26FBRVOE3ZFCB5F3FTGXEGOV5CN7RAB6TRPJR"
display_decimals=7
name="USD1 Token"
desc="usd1"
image="https://dealway.netlify.app/logo.png"
